package rules 

import com.droolsUIEngine.droolsUIEngine.Models.SPAR_Investment_Horizon

rule "SPAR_Investment_Horizon_1"
when
    $a : SPAR_Investment_Horizon( HKRegulated == "Yes", Direction == "Buy", ProductType == "Funds", ProductSubType == "Exclude Mutual Funds", ExecutionType == "ALL", InvestmentHorizon == "B", ProductTenor == "A", Tenor == "GT2", VC == "Y", FundMasterList == "Y" )  
then
$a.setStatus("Hard Block");

end


