package rules 

import com.droolsUIEngine.droolsUIEngine.Models.SPAR_PRR_CPR

rule "SPAR_PRR_CPR_13"
when
    $a : SPAR_PRR_CPR( HKRegulated == "No", Direction == "Buy", ProductType == "Funds", ProductSubType == "Exclude Mutual Funds", HYBFIndicator == "ALL", ExecutionType == "ALL", VCStatus == "B", HedgingIndicator == "A", CPR == 1, PRR == 2, IsPRRMoreThanOREqualsToCPR == "GT2" )  
then
$a.setStatus("Soft Block");

end


