export const INVESTMENT_HORIZON = {
  hkRegulated: ['Yes', 'No'],
  direction: ['Buy', 'Sell'],
  productType: [
    'Bonds',
    'Funds',
    'IPO Bonds',
    'Equities',
    'IPO Equities',
    'FX Forwards',
    'FX Derivate',
    'Equity Derivative',
    'Loans',
    'Deposits',
    'FX Swaps',
    'FX Spots',
  ],
  productSubType: ['ALL', 'Mutual Funds', 'Exclude Mutual Funds', ''],
  executionType: ['ADV', 'EXE', 'ALL'],
  investmentHorizon: [
    'A',
    'B',
    'C',
    'D',
    'Missing',
    'A, B, C',
    'B, C, D',
    'C, D',
    'ALL',
    'NA',
  ],
  productTenor: ['A', 'B', 'C', 'D', 'Missing', 'NA', 'ALL', 'B, C, D', 'C, D'],
  tenor: [
    'Missing',
    'Invalid',
    'GT1',
    'GT2',
    'GT3',
    'GT4',
    'GT5',
    'GT6',
    'GT7',
    'GT8',
    'GT9',
    'GT10',
    'LTEQ1',
    'LTEQ2',
    'LTEQ3',
    'LTEQ4',
    'LTEQ5',
    'LTEQ6',
    'LTEQ7',
    'LTEQ8',
    'LTEQ9',
    'LTEQ10',
    'NA',
  ],
  vcStatus: ['Y', 'N', 'ALL', 'NA'],
  fundMasterList: ['Y', 'N', 'ALL', 'NA'],
}

export const INVESTMENT_HORIZON_MAPPING = {
  hkRegulated: 'HK Regulated',
  direction: 'Direction',
  productType: 'Product Type',
  productSubType: 'Product Sub Type',
  executionType: 'Execution Type',
  investmentHorizon: 'Investment Horizon',
  productTenor: 'Product Tenor',
  tenor: 'Tenor',
  vcStatus: 'VC Status',
  fundMasterList: 'Fund Master List',
}
